Repository huamanraj/aitoolbox.software, pull requests merged in 2025-08, with the labels that each got.

#48 Fix Responsiveness and Add seo content
  src/app/(Tools)/ai-translator/_components/translator-client.tsx
  src/app/(Tools)/ai-translator/_components/translator-form.tsx
  src/app/(Tools)/ai-translator/_components/translator-output.tsx
  src/app/(Tools)/ai-translator/page.tsx
  src/app/(Tools)/app-idea-generator/_components/app-idea-generator-client.tsx
  src/app/(Tools)/app-idea-generator/_components/app-idea-generator-form.tsx
  src/app/(Tools)/app-idea-generator/_components/app-idea-generator-output.tsx
  src/app/(Tools)/app-idea-generator/page.tsx
  src/app/(Tools)/blog-idea-generator/_components/blog-idea-generator-client.tsx
  src/app/(Tools)/blog-idea-generator/_components/blog-idea-generator-form.tsx
  src/app/(Tools)/blog-idea-generator/_components/blog-idea-generator-output.tsx
  src/app/(Tools)/blog-idea-generator/page.tsx
  src/app/(Tools)/blog-writer/_components/blog-writer-client.tsx
  src/app/(Tools)/blog-writer/_components/blog-writer-form.tsx
  src/app/(Tools)/blog-writer/_components/blog-writer-output.tsx
  src/app/(Tools)/blog-writer/page.tsx
  src/app/(Tools)/grammar-fixer/_components/grammar-fixer-client.tsx
  src/app/(Tools)/idea-generator/_components/idea-generator-client.tsx
  src/app/(Tools)/idea-generator/_components/idea-generator-form.tsx
  src/app/(Tools)/idea-generator/_components/idea-generator-output.tsx
  src/app/(Tools)/idea-generator/page.tsx
  src/app/(Tools)/image-generator/page.tsx
  src/app/(Tools)/logo-generator/_components/logo-generator-client.tsx
  src/app/(Tools)/product-idea-generator/_components/product-idea-generator-client.tsx
  src/app/(Tools)/product-idea-generator/_components/product-idea-generator-form.tsx
  src/app/(Tools)/product-idea-generator/_components/product-idea-generator-output.tsx
  src/app/(Tools)/startup-idea-generator/_components/startup-idea-generator-client.tsx
  src/app/(Tools)/startup-idea-generator/_components/startup-idea-generator-form.tsx
  src/app/(Tools)/startup-idea-generator/_components/startup-idea-generator-output.tsx
  src/app/(Tools)/startup-idea-generator/page.tsx
  src/app/(Tools)/youtube-idea-generator/_components/youtube-idea-generator-client.tsx
  src/app/(Tools)/youtube-idea-generator/_components/youtube-idea-generator-form.tsx
  src/app/(Tools)/youtube-idea-generator/_components/youtube-idea-generator-output.tsx
Labels: gssoc25, level3, PA Approved, Mentor Approved

#54 Fix/quick action buttons
  package-lock.json
  src/components/realtime-chat.tsx
Labels: gssoc25, level2, PA Approved, Mentor Approved

#55 Adding the feature of project recommender
  src/app/(Tools)/project-recommender/_components/project-recommender-client.tsx
  src/app/(Tools)/project-recommender/_components/project-recommender-form.tsx
  src/app/(Tools)/project-recommender/_components/project-recommender-output.tsx
  src/app/(Tools)/project-recommender/layout.tsx
  src/app/(Tools)/project-recommender/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/common/Footer.tsx
  src/components/common/Sidebar.tsx
Labels: gssoc25, level3, PA Approved, Mentor Approved

#24 Gssoc25 #15
  .github/workflows/auto-reply.yml
  src/app/(Tools)/ai-translator/_components/translator-client.tsx
  src/app/(Tools)/ai-translator/_components/translator-form.tsx
  src/app/(Tools)/ai-translator/page.tsx
  src/components/common/Sidebar.tsx
Labels: gssoc25, level3, PA Approved, Mentor Approved

#72 SECURITY.md
  SECURITY.md
Labels: gssoc25, level1, PA Approved, Mentor Approved

#66 ai bio generator added
  src/app/(Tools)/ai-bio-generator/components/bio-generator-client.tsx
  src/app/(Tools)/ai-bio-generator/components/bio-generator-form.tsx
  src/app/(Tools)/ai-bio-generator/components/bio-generator-output.tsx
  src/app/(Tools)/ai-bio-generator/page.tsx
  src/app/page.tsx
  src/app/sitemap.ts
  src/components/common/Sidebar.tsx
Labels: gssoc25, level3, PA Approved, Mentor Approved

#75 Build the product description page
  src/app/(Tools)/product-description-generator/_components/product-description-client.tsx
  src/app/(Tools)/product-description-generator/_components/product-description-form.tsx
  src/app/(Tools)/product-description-generator/_components/product-description-output.tsx
  src/app/(Tools)/product-description-generator/layout.tsx
  src/app/(Tools)/product-description-generator/page.tsx
  src/app/api/product-description/route.ts
  src/components/common/Sidebar.tsx
Labels: gssoc25, level3, PA Approved, Mentor Approved

#82 feat: add NativeBannerAd to all tool pages as per layout guidelines
  package-lock.json
  src/app/(Tools)/ai-bio-generator/components/bio-generator-client.tsx
  src/app/(Tools)/ai-translator/_components/translator-client.tsx
  src/app/(Tools)/anime-ai-generator/_components/anime-generator-client.tsx
  src/app/(Tools)/app-idea-generator/_components/app-idea-generator-client.tsx
  src/app/(Tools)/blog-idea-generator/_components/blog-idea-generator-client.tsx
  src/app/(Tools)/blog-writer/_components/blog-writer-client.tsx
  src/app/(Tools)/code-explainer/code-explainer-client.tsx
  src/app/(Tools)/email-writer/_components/email-writer-client.tsx
  src/app/(Tools)/grammar-fixer/_components/grammar-fixer-client.tsx
  src/app/(Tools)/idea-generator/_components/idea-generator-client.tsx
  src/app/(Tools)/image-generator/_components/image-generator-client.tsx
  src/app/(Tools)/linkedin-post-generator/_components/linkedin-post-generator-client.tsx
  src/app/(Tools)/logo-generator/_components/logo-generator-client.tsx
  src/app/(Tools)/product-idea-generator/_components/product-idea-generator-client.tsx
  src/app/(Tools)/project-recommender/_components/project-recommender-client.tsx
  src/app/(Tools)/prompt-generator/_components/prompt-generator-client.tsx
  src/app/(Tools)/resume-builder/_components/Resume-builder-client.tsx
  src/app/(Tools)/startup-idea-generator/_components/startup-idea-generator-client.tsx
  src/app/(Tools)/text-summarizer/_components/text-summarizer-client.tsx
  src/app/(Tools)/trip-planner/_components/trip-planner-client.tsx
  src/app/(Tools)/youtube-idea-generator/_components/youtube-idea-generator-client.tsx
  src/components/NativeBannerAd.tsx
Labels: gssoc25, level3

#104 Add Cover Letter Generator Feature
  src/app/(Tools)/cover-letter-generator/_components/cover-letter-client.tsx
  src/app/(Tools)/cover-letter-generator/_components/cover-letter-form.tsx
  src/app/(Tools)/cover-letter-generator/_components/cover-letter-output.tsx
  src/app/(Tools)/cover-letter-generator/page.tsx
  src/app/(blogs)/ai-cover-letter-guide/layout.tsx
  src/app/(blogs)/ai-cover-letter-guide/page.tsx
  src/app/api/cover-letter/route.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/components/common/Sidebar.tsx
Labels: gssoc25, level3, PA Approved, Mentor Approved
