Repository huamanraj/aitoolbox.software, pull requests merged in 2025-07, with the labels that each got.

#20 Add GitHub Action to Auto-Comment on New Issues (#10)
  .github/workflows/auto-reply.yml
Labels: gssoc, level1

#38 Add AI Trip Planner feature to navigation
  src/app/(Tools)/trip-planner/_components/trip-planner-client.tsx
  src/app/(Tools)/trip-planner/_components/trip-planner-form.tsx
  src/app/(Tools)/trip-planner/_components/trip-planner-output.tsx
  src/app/(Tools)/trip-planner/layout.tsx
  src/app/(Tools)/trip-planner/page.tsx
  src/app/layout.tsx
  src/app/page.tsx
  src/components/common/Sidebar.tsx
Labels: gssoc, level3, AP Approved, Mentor Approved

#41 Resume Builder Feature
  package-lock.json
  package.json
  src/app/(Tools)/resume-builder/_components/AboutResumebuilder.tsx
  src/app/(Tools)/resume-builder/_components/BorderStyleButtons.tsx
  src/app/(Tools)/resume-builder/_components/Loader.tsx
  src/app/(Tools)/resume-builder/_components/LoadingButton.tsx
  src/app/(Tools)/resume-builder/_components/OptionMenu.tsx
  src/app/(Tools)/resume-builder/_components/Resume-builder-client.tsx
  src/app/(Tools)/resume-builder/_components/ResumeForm.tsx
  src/app/(Tools)/resume-builder/_components/ResumePreview.tsx
  src/app/(Tools)/resume-builder/_components/ResumePreviewSection.tsx
  src/app/(Tools)/resume-builder/_components/forms/EducationForm.tsx
  src/app/(Tools)/resume-builder/_components/forms/GeneralInfoForm.tsx
  src/app/(Tools)/resume-builder/_components/forms/PersonalInfoForm.tsx
  src/app/(Tools)/resume-builder/_components/forms/SkillsForm.tsx
  src/app/(Tools)/resume-builder/_components/forms/SummaryForm.tsx
  src/app/(Tools)/resume-builder/_components/forms/WorkExperienceForm.tsx
  src/app/(Tools)/resume-builder/constant.ts
  src/app/(Tools)/resume-builder/layout.tsx
  src/app/(Tools)/resume-builder/page.tsx
  src/contexts/resume-context.tsx
  src/hooks/use-demension.tsx
  src/lib/resume/validation.ts
  src/types/types.ts
Labels: gssoc, level3, PA Approved, Mentor Approved
